name: Flask Lint

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r hw/requirements.txt


      - name: Run Flake8
        run: flake8 hw/app

      - name: Run Black
        run: black --check hw

      - name: Run isort
        run: isort --check-only --profile black hw

      - name: Run tests
        run: pytest hw/tests
