name: Flask Lint

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: my_db_test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r module_29_testing/hw/requirements.txt


      - name: Run isort
        run: isort --profile black --src module_29_testing/hw module_29_testing/hw

      - name: Run Black
        run: black --check module_29_testing/hw

      - name: Run Flake8
        run: flake8 --max-line-length=88 --extend-ignore=E203,E501,W503 module_29_testing/hw/app

      - name: Run tests
        run: pytest module_29_testing/hw/tests
